name: Test Builder

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: |
          export CGO_ENABLED=0

          export GOOS=linux GOARCH=amd64
          go test -c
          mv benchmark.test benchmark_linux_x86_64

          export GOOS=linux GOARCH=arm
          go test -c
          mv benchmark.test benchmark_linux_arm

          export GOOS=linux GOARCH=arm64
          go test -c
          mv benchmark.test benchmark_linux_arm64

          export GOOS=linux GOARCH=mips
          go test -c
          mv benchmark.test benchmark_linux_mips

          export GOOS=linux GOARCH=mips GOMIPS=softfloat
          go test -c
          mv benchmark.test benchmark_linux_mips_softfloat

          export GOOS=windows GOARCH=amd64
          go test -c
          mv benchmark.test.exe benchmark_windows_x86_64.exe

          export GOOS=darwin GOARCH=amd64
          go test -c
          mv benchmark.test benchmark_darwin_x86_64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Benchmarks
          path: ./benchmark_*
