name: Test Builder

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: |
          export CGO_ENABLED=0

          go test -c
          mv benchmark.test benchmark_x86_64

          export GOARCH=arm
          go test -c
          mv benchmark.test benchmark_arm

          export GOARCH=arm64
          go test -c
          mv benchmark.test benchmark_arm64

          export GOARCH=mips GOMIPS=softfloat
          go test -c
          mv benchmark.test benchmark_mips_softfloat

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Benchmarks
          path: ./benchmark_*
